export type PreTriageHeuristic = {
  id: string;
  description: string;
  pattern: RegExp;
};

export const PRETRIAGE_HEURISTICS: PreTriageHeuristic[] = [
  { id: "ps_encoded_command", description: "PowerShell encoded command usage", pattern: new RegExp("powershell\\s+-enc(odedcommand)?", "i") },
  { id: "ps_execution_policy_bypass", description: "PowerShell execution policy bypass", pattern: new RegExp("-executionpolicy\\s+bypass", "i") },
  { id: "cmd_from_powershell", description: "PowerShell launching cmd", pattern: new RegExp("powershell.*cmd\\.exe", "i") },
  { id: "mshta_invocation", description: "MSHTA execution chain", pattern: new RegExp("mshta(\\.exe)?", "i") },
  { id: "regsvr32_silent", description: "Regsvr32 silent registration", pattern: new RegExp("regsvr32(\\.exe)?\\s+/s", "i") },
  { id: "rundll32_launch", description: "Rundll32 execution chain", pattern: new RegExp("rundll32(\\.exe)?", "i") },
  { id: "wmic_process_create", description: "WMIC process creation", pattern: new RegExp("wmic\\s+process\\s+call\\s+create", "i") },
  { id: "bitsadmin_transfer", description: "BITSAdmin transfer pattern", pattern: new RegExp("bitsadmin\\s+/transfer", "i") },
  { id: "certutil_decode", description: "Certutil decode or urlcache usage", pattern: new RegExp("certutil\\s+-(decode|urlcache)", "i") },
  { id: "schtasks_create", description: "Scheduled task persistence", pattern: new RegExp("schtasks\\s+/create", "i") },
  { id: "at_job_create", description: "Legacy at job persistence", pattern: new RegExp("\\bat\\s+\\d{1,2}:\\d{2}", "i") },
  { id: "reg_run_key", description: "Registry Run key persistence", pattern: new RegExp("\\\\currentversion\\\\run", "i") },
  { id: "reg_runonce_key", description: "Registry RunOnce persistence", pattern: new RegExp("\\\\currentversion\\\\runonce", "i") },
  { id: "wscript_launch", description: "WSH script execution via wscript", pattern: new RegExp("wscript(\\.exe)?", "i") },
  { id: "cscript_launch", description: "WSH script execution via cscript", pattern: new RegExp("cscript(\\.exe)?", "i") },
  { id: "hta_file_drop", description: "HTA payload reference", pattern: new RegExp("\\.hta\\b", "i") },
  { id: "js_file_drop", description: "JavaScript payload reference", pattern: new RegExp("\\.js\\b", "i") },
  { id: "vbs_file_drop", description: "VBScript payload reference", pattern: new RegExp("\\.vbs\\b", "i") },
  { id: "ps1_file_drop", description: "PowerShell script reference", pattern: new RegExp("\\.ps1\\b", "i") },
  { id: "dll_file_drop", description: "DLL payload reference", pattern: new RegExp("\\.dll\\b", "i") },
  { id: "scr_file_drop", description: "Screensaver payload reference", pattern: new RegExp("\\.scr\\b", "i") },
  { id: "bat_file_drop", description: "Batch payload reference", pattern: new RegExp("\\.bat\\b", "i") },
  { id: "cmd_file_drop", description: "CMD payload reference", pattern: new RegExp("\\.cmd\\b", "i") },
  { id: "zip_archive_drop", description: "ZIP archive payload", pattern: new RegExp("\\.zip\\b", "i") },
  { id: "iso_archive_drop", description: "ISO archive payload", pattern: new RegExp("\\.iso\\b", "i") },
  { id: "img_archive_drop", description: "IMG disk image payload", pattern: new RegExp("\\.img\\b", "i") },
  { id: "rar_archive_drop", description: "RAR archive payload", pattern: new RegExp("\\.rar\\b", "i") },
  { id: "7z_archive_drop", description: "7z archive payload", pattern: new RegExp("\\.7z\\b", "i") },
  { id: "powershell_downloadstring", description: "PowerShell DownloadString usage", pattern: new RegExp("downloadstring\\s*\\(", "i") },
  { id: "powershell_invoke_expression", description: "PowerShell Invoke-Expression usage", pattern: new RegExp("invoke-expression", "i") },
  { id: "frombase64string_usage", description: "Base64 decode in script", pattern: new RegExp("frombase64string\\s*\\(", "i") },
  { id: "iex_alias_usage", description: "IEX alias usage", pattern: new RegExp("\\biex\\b", "i") },
  { id: "new_object_net_webclient", description: "WebClient download primitive", pattern: new RegExp("new-object\\s+net\\.webclient", "i") },
  { id: "invoke_webrequest_usage", description: "Invoke-WebRequest usage", pattern: new RegExp("invoke-webrequest", "i") },
  { id: "invoke_restmethod_usage", description: "Invoke-RestMethod usage", pattern: new RegExp("invoke-restmethod", "i") },
  { id: "curl_usage", description: "Curl command usage", pattern: new RegExp("\\bcurl\\b", "i") },
  { id: "wget_usage", description: "Wget command usage", pattern: new RegExp("\\bwget\\b", "i") },
  { id: "http_plain_download", description: "Plain HTTP URL present", pattern: new RegExp("http://", "i") },
  { id: "pastebin_reference", description: "Pastebin indicator", pattern: new RegExp("pastebin\\.com", "i") },
  { id: "github_raw_reference", description: "GitHub raw payload indicator", pattern: new RegExp("raw\\.githubusercontent\\.com", "i") },
  { id: "telegram_api_reference", description: "Telegram API indicator", pattern: new RegExp("api\\.telegram\\.org", "i") },
  { id: "discord_cdn_reference", description: "Discord CDN indicator", pattern: new RegExp("cdn\\.discordapp\\.com", "i") },
  { id: "tor_onion_reference", description: "Onion service indicator", pattern: new RegExp("\\.onion\\b", "i") },
  { id: "base64_blob_long", description: "Long base64-like blob", pattern: new RegExp("[A-Za-z0-9+/]{120,}={0,2}", "g") },
  { id: "hex_blob_long", description: "Long hex-like blob", pattern: new RegExp("[A-Fa-f0-9]{128,}", "g") },
  { id: "url_shortener_bitly", description: "URL shortener bitly indicator", pattern: new RegExp("bit\\.ly", "i") },
  { id: "url_shortener_tinyurl", description: "URL shortener tinyurl indicator", pattern: new RegExp("tinyurl\\.com", "i") },
  { id: "lolbin_makecab", description: "LOLBIN makecab usage", pattern: new RegExp("makecab(\\.exe)?", "i") },
  { id: "lolbin_expand", description: "LOLBIN expand usage", pattern: new RegExp("expand(\\.exe)?", "i") },
  { id: "lolbin_msbuild", description: "LOLBIN msbuild usage", pattern: new RegExp("msbuild(\\.exe)?", "i") },
  { id: "suspicious_tld_ru", description: "Suspicious RU TLD reference", pattern: new RegExp("\\.ru\\b", "i") },
  { id: "suspicious_tld_su", description: "Suspicious SU TLD reference", pattern: new RegExp("\\.su\\b", "i") },
  { id: "suspicious_tld_cn", description: "Suspicious CN TLD reference", pattern: new RegExp("\\.cn\\b", "i") },
  { id: "suspicious_tld_top", description: "Suspicious TOP TLD reference", pattern: new RegExp("\\.top\\b", "i") },
  { id: "suspicious_tld_xyz", description: "Suspicious XYZ TLD reference", pattern: new RegExp("\\.xyz\\b", "i") },
  { id: "suspicious_tld_zip", description: "Suspicious ZIP TLD reference", pattern: new RegExp("\\.zip\\b", "i") },
  { id: "suspicious_tld_click", description: "Suspicious CLICK TLD reference", pattern: new RegExp("\\.click\\b", "i") },
  { id: "suspicious_tld_cam", description: "Suspicious CAM TLD reference", pattern: new RegExp("\\.cam\\b", "i") },
  { id: "suspicious_tld_gq", description: "Suspicious GQ TLD reference", pattern: new RegExp("\\.gq\\b", "i") },
  { id: "suspicious_tld_ml", description: "Suspicious ML TLD reference", pattern: new RegExp("\\.ml\\b", "i") },
  { id: "suspicious_tld_cf", description: "Suspicious CF TLD reference", pattern: new RegExp("\\.cf\\b", "i") },
  { id: "suspicious_tld_tk", description: "Suspicious TK TLD reference", pattern: new RegExp("\\.tk\\b", "i") },
  { id: "url_ip_literal", description: "URL with IP literal host", pattern: new RegExp("https?://\\d{1,3}(?:\\.\\d{1,3}){3}", "i") },
  { id: "url_nonstandard_port", description: "URL with non-standard port", pattern: new RegExp("https?://[^\\s/:]+:(?!80\\b", "443\\b)\\d{2,5}|i") },
  { id: "dns_txt_record_hint", description: "DNS TXT record manipulation hint", pattern: new RegExp("\\bdns\\s+txt\\b", "i") },
  { id: "powershell_bypass_hidden", description: "PowerShell hidden window usage", pattern: new RegExp("-windowstyle\\s+hidden", "i") },
  { id: "powershell_noprofile", description: "PowerShell -NoProfile usage", pattern: new RegExp("-noprofile", "i") },
  { id: "powershell_noninteractive", description: "PowerShell -NonInteractive usage", pattern: new RegExp("-noninteractive", "i") },
  { id: "powershell_noni_abbrev", description: "PowerShell -noni abbreviation", pattern: new RegExp("\\s-noni\\b", "i") },
  { id: "powershell_w_hidden", description: "PowerShell -w hidden usage", pattern: new RegExp("\\s-w\\s+hidden", "i") },
  { id: "encoded_scriptblock", description: "Encoded scriptblock marker", pattern: new RegExp("\\$encodedcommand", "i") },
  { id: "download_to_temp", description: "Download path pointing to temp", pattern: new RegExp("\\\	emp\\\\", "i") },
  { id: "appdata_execution", description: "Execution from AppData path", pattern: new RegExp("\\\\\appdata\\\\", "i") },
  { id: "programdata_execution", description: "Execution from ProgramData path", pattern: new RegExp("\\\\\programdata\\\\", "i") },
  { id: "public_user_execution", description: "Execution from Public user folder", pattern: new RegExp("\\\\\users\\\\public\\\\", "i") },
  { id: "startup_folder_persistence", description: "Startup folder persistence path", pattern: new RegExp("\\\\\start menu\\\\programs\\\\startup", "i") },
  { id: "run_key_hkcu_short", description: "HKCU Run key short path", pattern: new RegExp("hkcu\\\\software\\\\microsoft\\\\windows\\\\currentversion\\\\run", "i") },
  { id: "run_key_hklm_short", description: "HKLM Run key short path", pattern: new RegExp("hklm\\\\software\\\\microsoft\\\\windows\\\\currentversion\\\\run", "i") },
  { id: "taskcache_reference", description: "TaskCache persistence reference", pattern: new RegExp("taskcache", "i") },
  { id: "service_create_sc", description: "Service creation via sc.exe", pattern: new RegExp("sc\\s+create\\s+", "i") },
  { id: "service_config_sc", description: "Service config via sc.exe", pattern: new RegExp("sc\\s+config\\s+", "i") },
  { id: "net_user_add", description: "User creation via net user", pattern: new RegExp("net\\s+user\\s+.+\\s+/add", "i") },
  { id: "net_localgroup_admin", description: "Admin group assignment", pattern: new RegExp("net\\s+localgroup\\s+administrators", "i") },
  { id: "whoami_priv", description: "Privilege discovery whoami", pattern: new RegExp("whoami\\s+/priv", "i") },
  { id: "ipconfig_all", description: "Network discovery ipconfig /all", pattern: new RegExp("ipconfig\\s+/all", "i") },
  { id: "arp_scan", description: "ARP table query", pattern: new RegExp("\\barp\\s+-a\\b", "i") },
  { id: "netstat_scan", description: "Network sockets netstat", pattern: new RegExp("netstat\\s+-an", "i") },
  { id: "nslookup_usage", description: "DNS lookup usage", pattern: new RegExp("\\bnslookup\\b", "i") },
  { id: "tracert_usage", description: "Route tracing usage", pattern: new RegExp("\\btracert\\b", "i") },
  { id: "route_print_usage", description: "Route table dump", pattern: new RegExp("route\\s+print", "i") },
  { id: "wevtutil_clearlog", description: "Event log clearing", pattern: new RegExp("wevtutil\\s+cl", "i") },
  { id: "vssadmin_delete", description: "Shadow copy deletion", pattern: new RegExp("vssadmin\\s+delete\\s+shadows", "i") },
  { id: "wbadmin_delete", description: "Backup catalog deletion", pattern: new RegExp("wbadmin\\s+delete\\s+catalog", "i") },
  { id: "bcdedit_recovery_off", description: "Recovery disable via bcdedit", pattern: new RegExp("bcdedit\\s+/set\\s+\\{default\\}\\s+recoveryenabled\\s+no", "i") },
  { id: "bcdedit_bootstatus_ignore", description: "Bootstatus ignore failures", pattern: new RegExp("bcdedit\\s+/set\\s+\\{default\\}\\s+bootstatuspolicy\\s+ignoreallfailures", "i") },
  { id: "ransom_note_marker", description: "Common ransom note marker", pattern: new RegExp("readme\\.(txt", "hta)|i") },
];
