import type { Plugin, OperationRegistry } from "@cybermasterchef/core";
import { toBase64 } from "./ops/toBase64.js";
import { fromBase64 } from "./ops/fromBase64.js";
import { toHex } from "./ops/toHex.js";
import { fromHex } from "./ops/fromHex.js";
import { sha256 } from "./ops/sha256.js";
import { toBinary } from "./ops/toBinary.js";
import { fromBinary } from "./ops/fromBinary.js";
import { urlEncode } from "./ops/urlEncode.js";
import { urlDecode } from "./ops/urlDecode.js";
import { reverse } from "./ops/reverse.js";
import { lowercase } from "./ops/lowercase.js";
import { uppercase } from "./ops/uppercase.js";
import { trim } from "./ops/trim.js";
import { prepend } from "./ops/prepend.js";
import { append } from "./ops/append.js";
import { replace } from "./ops/replace.js";
import { slice } from "./ops/slice.js";
import { repeat } from "./ops/repeat.js";
import { padStart } from "./ops/padStart.js";
import { padEnd } from "./ops/padEnd.js";
import { trimStart } from "./ops/trimStart.js";
import { trimEnd } from "./ops/trimEnd.js";
import { length } from "./ops/length.js";
import { wordCount } from "./ops/wordCount.js";
import { lineCount } from "./ops/lineCount.js";
import { firstLine } from "./ops/firstLine.js";
import { lastLine } from "./ops/lastLine.js";
import { normalizeWhitespace } from "./ops/normalizeWhitespace.js";
import { removeBlankLines } from "./ops/removeBlankLines.js";
import { startsWith } from "./ops/startsWith.js";

import { swapCase } from "./ops/swapCase.js";
import { removeSpaces } from "./ops/removeSpaces.js";
import { keepDigits } from "./ops/keepDigits.js";
import { removeDigits } from "./ops/removeDigits.js";
import { keepLetters } from "./ops/keepLetters.js";
import { removeLetters } from "./ops/removeLetters.js";
export const standardPlugin: Plugin = {
  pluginId: "plugins-standard",
  version: "0.1.0",
  register(registry: OperationRegistry): void {
    registry.register(toBase64);
    registry.register(fromBase64);
    registry.register(toHex);
    registry.register(fromHex);
    registry.register(toBinary);
    registry.register(fromBinary);
    registry.register(urlEncode);
    registry.register(urlDecode);
    registry.register(reverse);
    registry.register(lowercase);
    registry.register(uppercase);
    registry.register(trim);
    registry.register(prepend);
    registry.register(append);
    registry.register(replace);
    registry.register(slice);
    registry.register(repeat);
    registry.register(padStart);
    registry.register(padEnd);
    registry.register(trimStart);
    registry.register(trimEnd);
    registry.register(length);
    registry.register(wordCount);
    registry.register(lineCount);
    registry.register(firstLine);
    registry.register(lastLine);
    registry.register(normalizeWhitespace);
    registry.register(removeBlankLines);
    registry.register(startsWith);
    registry.register(swapCase);
    registry.register(removeSpaces);
    registry.register(keepDigits);
    registry.register(removeDigits);
    registry.register(keepLetters);
    registry.register(removeLetters);
    registry.register(sha256);
  }
};
