import type { Plugin, OperationRegistry } from "@cybermasterchef/core";
import { toBase64 } from "./ops/toBase64.js";
import { fromBase64 } from "./ops/fromBase64.js";
import { toHex } from "./ops/toHex.js";
import { fromHex } from "./ops/fromHex.js";
import { sha256 } from "./ops/sha256.js";
import { toBinary } from "./ops/toBinary.js";
import { fromBinary } from "./ops/fromBinary.js";
import { urlEncode } from "./ops/urlEncode.js";
import { urlDecode } from "./ops/urlDecode.js";
import { reverse } from "./ops/reverse.js";
import { lowercase } from "./ops/lowercase.js";
import { uppercase } from "./ops/uppercase.js";
import { trim } from "./ops/trim.js";
import { prepend } from "./ops/prepend.js";
import { append } from "./ops/append.js";
import { replace } from "./ops/replace.js";
import { slice } from "./ops/slice.js";
import { repeat } from "./ops/repeat.js";
import { padStart } from "./ops/padStart.js";
import { padEnd } from "./ops/padEnd.js";
import { trimStart } from "./ops/trimStart.js";
import { trimEnd } from "./ops/trimEnd.js";
import { length } from "./ops/length.js";
import { wordCount } from "./ops/wordCount.js";
import { lineCount } from "./ops/lineCount.js";
import { firstLine } from "./ops/firstLine.js";
import { lastLine } from "./ops/lastLine.js";
import { normalizeWhitespace } from "./ops/normalizeWhitespace.js";
import { removeBlankLines } from "./ops/removeBlankLines.js";
import { startsWith } from "./ops/startsWith.js";

import { swapCase } from "./ops/swapCase.js";
import { removeSpaces } from "./ops/removeSpaces.js";
import { keepDigits } from "./ops/keepDigits.js";
import { removeDigits } from "./ops/removeDigits.js";
import { keepLetters } from "./ops/keepLetters.js";
import { removeLetters } from "./ops/removeLetters.js";
import { keepAlnum } from "./ops/keepAlnum.js";
import { removeAlnum } from "./ops/removeAlnum.js";
import { toTitleCase } from "./ops/toTitleCase.js";
import { reverseLines } from "./ops/reverseLines.js";
import { sortLines } from "./ops/sortLines.js";
import { uniqueLines } from "./ops/uniqueLines.js";
import { trimLines } from "./ops/trimLines.js";
import { toSnakeCase } from "./ops/toSnakeCase.js";
import { toKebabCase } from "./ops/toKebabCase.js";
import { toCamelCase } from "./ops/toCamelCase.js";
import { toPascalCase } from "./ops/toPascalCase.js";
import { compactLines } from "./ops/compactLines.js";
import { reverseWords } from "./ops/reverseWords.js";
import { sortWords } from "./ops/sortWords.js";
import { uniqueWords } from "./ops/uniqueWords.js";
import { removeVowels } from "./ops/removeVowels.js";
import { keepVowels } from "./ops/keepVowels.js";
import { normalizeNewlines } from "./ops/normalizeNewlines.js";
import { endsWith } from "./ops/endsWith.js";
import { includesText } from "./ops/includesText.js";
import { lowerFirst } from "./ops/lowerFirst.js";
import { upperFirst } from "./ops/upperFirst.js";
import { removePunctuation } from "./ops/removePunctuation.js";
import { keepPunctuation } from "./ops/keepPunctuation.js";
import { collapseDashes } from "./ops/collapseDashes.js";
import { collapseUnderscores } from "./ops/collapseUnderscores.js";
import { removeTabs } from "./ops/removeTabs.js";
import { tabsToSpaces } from "./ops/tabsToSpaces.js";
import { spacesToTabs } from "./ops/spacesToTabs.js";
import { trimCommas } from "./ops/trimCommas.js";
import { trimQuotes } from "./ops/trimQuotes.js";
import { surroundBrackets } from "./ops/surroundBrackets.js";
import { surroundQuotes } from "./ops/surroundQuotes.js";
import { rot13 } from "./ops/rot13.js";
import { maskDigits } from "./ops/maskDigits.js";
import { removeNonAscii } from "./ops/removeNonAscii.js";
export const standardPlugin: Plugin = {
  pluginId: "plugins-standard",
  version: "0.1.0",
  register(registry: OperationRegistry): void {
    registry.register(toBase64);
    registry.register(fromBase64);
    registry.register(toHex);
    registry.register(fromHex);
    registry.register(toBinary);
    registry.register(fromBinary);
    registry.register(urlEncode);
    registry.register(urlDecode);
    registry.register(reverse);
    registry.register(lowercase);
    registry.register(uppercase);
    registry.register(trim);
    registry.register(prepend);
    registry.register(append);
    registry.register(replace);
    registry.register(slice);
    registry.register(repeat);
    registry.register(padStart);
    registry.register(padEnd);
    registry.register(trimStart);
    registry.register(trimEnd);
    registry.register(length);
    registry.register(wordCount);
    registry.register(lineCount);
    registry.register(firstLine);
    registry.register(lastLine);
    registry.register(normalizeWhitespace);
    registry.register(removeBlankLines);
    registry.register(startsWith);
    registry.register(swapCase);
    registry.register(removeSpaces);
    registry.register(keepDigits);
    registry.register(removeDigits);
    registry.register(keepLetters);
    registry.register(removeLetters);
    registry.register(keepAlnum);
    registry.register(removeAlnum);
    registry.register(toTitleCase);
    registry.register(reverseLines);
    registry.register(sortLines);
    registry.register(uniqueLines);
    registry.register(trimLines);
    registry.register(toSnakeCase);
    registry.register(toKebabCase);
    registry.register(toCamelCase);
    registry.register(toPascalCase);
    registry.register(compactLines);
    registry.register(reverseWords);
    registry.register(sortWords);
    registry.register(uniqueWords);
    registry.register(removeVowels);
    registry.register(keepVowels);
    registry.register(normalizeNewlines);
    registry.register(endsWith);
    registry.register(includesText);
    registry.register(lowerFirst);
    registry.register(upperFirst);
    registry.register(removePunctuation);
    registry.register(keepPunctuation);
    registry.register(collapseDashes);
    registry.register(collapseUnderscores);
    registry.register(removeTabs);
    registry.register(tabsToSpaces);
    registry.register(spacesToTabs);
    registry.register(trimCommas);
    registry.register(trimQuotes);
    registry.register(surroundBrackets);
    registry.register(surroundQuotes);
    registry.register(rot13);
    registry.register(maskDigits);
    registry.register(removeNonAscii);
    registry.register(sha256);
  }
};
