import "./third-party.d.ts";
import type { Plugin, OperationRegistry } from "@cybermasterchef/core";
import { toBase64 } from "./ops/toBase64.js";
import { fromBase64 } from "./ops/fromBase64.js";
import { toBase32 } from "./ops/toBase32.js";
import { fromBase32 } from "./ops/fromBase32.js";
import { toBase45 } from "./ops/toBase45.js";
import { fromBase45 } from "./ops/fromBase45.js";
import { toBase62 } from "./ops/toBase62.js";
import { fromBase62 } from "./ops/fromBase62.js";
import { toBase85 } from "./ops/toBase85.js";
import { fromBase85 } from "./ops/fromBase85.js";
import { toBech32 } from "./ops/toBech32.js";
import { fromBech32 } from "./ops/fromBech32.js";
import { toBase58 } from "./ops/toBase58.js";
import { fromBase58 } from "./ops/fromBase58.js";
import { toBase92 } from "./ops/toBase92.js";
import { fromBase92 } from "./ops/fromBase92.js";
import { toBraille } from "./ops/toBraille.js";
import { fromBraille } from "./ops/fromBraille.js";
import { toPunycode } from "./ops/toPunycode.js";
import { fromPunycode } from "./ops/fromPunycode.js";
import { toModhex } from "./ops/toModhex.js";
import { fromModhex } from "./ops/fromModhex.js";
import { toMorseCode } from "./ops/toMorseCode.js";
import { fromMorseCode } from "./ops/fromMorseCode.js";
import { toHex } from "./ops/toHex.js";
import { fromHex } from "./ops/fromHex.js";
import { sha256 } from "./ops/sha256.js";
import { sha224 } from "./ops/sha224.js";
import { toBinary } from "./ops/toBinary.js";
import { fromBinary } from "./ops/fromBinary.js";
import { toCharcode } from "./ops/toCharcode.js";
import { fromCharcode } from "./ops/fromCharcode.js";
import { toDecimal } from "./ops/toDecimal.js";
import { fromDecimal } from "./ops/fromDecimal.js";
import { toOctal } from "./ops/toOctal.js";
import { fromOctal } from "./ops/fromOctal.js";
import { toHexContent } from "./ops/toHexContent.js";
import { fromHexContent } from "./ops/fromHexContent.js";
import { dropBytes } from "./ops/dropBytes.js";
import { takeBytes } from "./ops/takeBytes.js";
import { dropNthBytes } from "./ops/dropNthBytes.js";
import { takeNthBytes } from "./ops/takeNthBytes.js";
import { removeNullBytes } from "./ops/removeNullBytes.js";
import { bitShiftLeft } from "./ops/bitShiftLeft.js";
import { bitShiftRight } from "./ops/bitShiftRight.js";
import { urlEncode } from "./ops/urlEncode.js";
import { urlDecode } from "./ops/urlDecode.js";
import { reverse } from "./ops/reverse.js";
import { lowercase } from "./ops/lowercase.js";
import { uppercase } from "./ops/uppercase.js";
import { alternatingCaps } from "./ops/alternatingCaps.js";
import { expandAlphabetRange } from "./ops/expandAlphabetRange.js";
import { escapeString } from "./ops/escapeString.js";
import { trim } from "./ops/trim.js";
import { prepend } from "./ops/prepend.js";
import { append } from "./ops/append.js";
import { replace } from "./ops/replace.js";
import { slice } from "./ops/slice.js";
import { repeat } from "./ops/repeat.js";
import { padStart } from "./ops/padStart.js";
import { padEnd } from "./ops/padEnd.js";
import { trimStart } from "./ops/trimStart.js";
import { trimEnd } from "./ops/trimEnd.js";
import { length } from "./ops/length.js";
import { wordCount } from "./ops/wordCount.js";
import { lineCount } from "./ops/lineCount.js";
import { firstLine } from "./ops/firstLine.js";
import { lastLine } from "./ops/lastLine.js";
import { normalizeWhitespace } from "./ops/normalizeWhitespace.js";
import { removeBlankLines } from "./ops/removeBlankLines.js";
import { startsWith } from "./ops/startsWith.js";

import { swapCase } from "./ops/swapCase.js";
import { removeSpaces } from "./ops/removeSpaces.js";
import { keepDigits } from "./ops/keepDigits.js";
import { removeDigits } from "./ops/removeDigits.js";
import { keepLetters } from "./ops/keepLetters.js";
import { removeLetters } from "./ops/removeLetters.js";
import { keepAlnum } from "./ops/keepAlnum.js";
import { removeAlnum } from "./ops/removeAlnum.js";
import { toTitleCase } from "./ops/toTitleCase.js";
import { reverseLines } from "./ops/reverseLines.js";
import { sortLines } from "./ops/sortLines.js";
import { uniqueLines } from "./ops/uniqueLines.js";
import { trimLines } from "./ops/trimLines.js";
import { toSnakeCase } from "./ops/toSnakeCase.js";
import { toKebabCase } from "./ops/toKebabCase.js";
import { toCamelCase } from "./ops/toCamelCase.js";
import { toPascalCase } from "./ops/toPascalCase.js";
import { compactLines } from "./ops/compactLines.js";
import { reverseWords } from "./ops/reverseWords.js";
import { sortWords } from "./ops/sortWords.js";
import { uniqueWords } from "./ops/uniqueWords.js";
import { removeVowels } from "./ops/removeVowels.js";
import { keepVowels } from "./ops/keepVowels.js";
import { normalizeNewlines } from "./ops/normalizeNewlines.js";
import { endsWith } from "./ops/endsWith.js";
import { includesText } from "./ops/includesText.js";
import { lowerFirst } from "./ops/lowerFirst.js";
import { upperFirst } from "./ops/upperFirst.js";
import { removePunctuation } from "./ops/removePunctuation.js";
import { keepPunctuation } from "./ops/keepPunctuation.js";
import { collapseDashes } from "./ops/collapseDashes.js";
import { collapseUnderscores } from "./ops/collapseUnderscores.js";
import { removeTabs } from "./ops/removeTabs.js";
import { tabsToSpaces } from "./ops/tabsToSpaces.js";
import { spacesToTabs } from "./ops/spacesToTabs.js";
import { trimCommas } from "./ops/trimCommas.js";
import { trimQuotes } from "./ops/trimQuotes.js";
import { surroundBrackets } from "./ops/surroundBrackets.js";
import { surroundQuotes } from "./ops/surroundQuotes.js";
import { rot13 } from "./ops/rot13.js";
import { maskDigits } from "./ops/maskDigits.js";
import { removeNonAscii } from "./ops/removeNonAscii.js";
import { keepNonAscii } from "./ops/keepNonAscii.js";
import { reverseCharsInWords } from "./ops/reverseCharsInWords.js";
import { wordsToLines } from "./ops/wordsToLines.js";
import { linesToWords } from "./ops/linesToWords.js";
import { linesToCsv } from "./ops/linesToCsv.js";
import { csvToLines } from "./ops/csvToLines.js";
import { stripAccents } from "./ops/stripAccents.js";
import { removeDoubleQuotes } from "./ops/removeDoubleQuotes.js";
import { removeSingleQuotes } from "./ops/removeSingleQuotes.js";
import { replaceNewlinesWithSpace } from "./ops/replaceNewlinesWithSpace.js";
import { replaceSpacesWithNewlines } from "./ops/replaceSpacesWithNewlines.js";
import { tabsToSingleSpace } from "./ops/tabsToSingleSpace.js";
import { countUppercase } from "./ops/countUppercase.js";
import { countLowercase } from "./ops/countLowercase.js";
import { countAscii } from "./ops/countAscii.js";
import { countNonAscii } from "./ops/countNonAscii.js";
import { countNonEmptyLines } from "./ops/countNonEmptyLines.js";
import { firstWord } from "./ops/firstWord.js";
import { lastWord } from "./ops/lastWord.js";
import { removeCommas } from "./ops/removeCommas.js";
import { removeDots } from "./ops/removeDots.js";
import { removeSemicolons } from "./ops/removeSemicolons.js";
import { keepHexChars } from "./ops/keepHexChars.js";
import { removeHexChars } from "./ops/removeHexChars.js";
import { onlyPrintableAscii } from "./ops/onlyPrintableAscii.js";
import { removeControlChars } from "./ops/removeControlChars.js";
import { collapseMultipleNewlines } from "./ops/collapseMultipleNewlines.js";
import { trimLeadingDots } from "./ops/trimLeadingDots.js";
import { trimTrailingDots } from "./ops/trimTrailingDots.js";
import { linesNumbered } from "./ops/linesNumbered.js";
import { removeColons } from "./ops/removeColons.js";
import { removeSlashes } from "./ops/removeSlashes.js";
import { removePipes } from "./ops/removePipes.js";
import { removeBackslashes } from "./ops/removeBackslashes.js";
import { removeAsterisks } from "./ops/removeAsterisks.js";
import { removeHashes } from "./ops/removeHashes.js";
import { removeAtSigns } from "./ops/removeAtSigns.js";
import { removeDollarSigns } from "./ops/removeDollarSigns.js";
import { removePercents } from "./ops/removePercents.js";
import { removeAmpersands } from "./ops/removeAmpersands.js";
import { removePluses } from "./ops/removePluses.js";
import { removeEquals } from "./ops/removeEquals.js";
import { removeTildes } from "./ops/removeTildes.js";
import { removeCarets } from "./ops/removeCarets.js";
import { removeBackticks } from "./ops/removeBackticks.js";
import { removeQuestionMarks } from "./ops/removeQuestionMarks.js";
import { removeExclamations } from "./ops/removeExclamations.js";
import { removeParentheses } from "./ops/removeParentheses.js";
import { removeBrackets } from "./ops/removeBrackets.js";
import { removeBraces } from "./ops/removeBraces.js";
import { removeAngles } from "./ops/removeAngles.js";
import { removeDoubleSpaces } from "./ops/removeDoubleSpaces.js";
import { linesTrimRight } from "./ops/linesTrimRight.js";
import { linesTrimLeft } from "./ops/linesTrimLeft.js";
import { removeDigitsAndSpaces } from "./ops/removeDigitsAndSpaces.js";
import { keepDigitsAndDots } from "./ops/keepDigitsAndDots.js";
import { removeEmojis } from "./ops/removeEmojis.js";
import { removeUnderscores } from "./ops/removeUnderscores.js";
import { removeHyphens } from "./ops/removeHyphens.js";
import { removeSpacesAndTabs } from "./ops/removeSpacesAndTabs.js";
import { keepWhitespace } from "./ops/keepWhitespace.js";
import { countTabs } from "./ops/countTabs.js";
import { countSpaces } from "./ops/countSpaces.js";
import { countCommas } from "./ops/countCommas.js";
import { countDots } from "./ops/countDots.js";
import { countColons } from "./ops/countColons.js";
import { countSemicolons } from "./ops/countSemicolons.js";
import { countSlashes } from "./ops/countSlashes.js";
import { countBackslashes } from "./ops/countBackslashes.js";
import { countPluses } from "./ops/countPluses.js";
import { countDashes } from "./ops/countDashes.js";
import { countQuestionMarks } from "./ops/countQuestionMarks.js";
import { countExclamations } from "./ops/countExclamations.js";
import { countBrackets } from "./ops/countBrackets.js";
import { countParentheses } from "./ops/countParentheses.js";
import { countQuotes } from "./ops/countQuotes.js";
import { countUnderscores } from "./ops/countUnderscores.js";
import { onlyLettersAndSpaces } from "./ops/onlyLettersAndSpaces.js";
import { onlyAlnumAndSpaces } from "./ops/onlyAlnumAndSpaces.js";
import { sum } from "./ops/sum.js";
import { subtract } from "./ops/subtract.js";
import { multiply } from "./ops/multiply.js";
import { divide } from "./ops/divide.js";
import { removeCurrencySymbols } from "./ops/removeCurrencySymbols.js";
import { removeMathSymbols } from "./ops/removeMathSymbols.js";
import { normalizeCommas } from "./ops/normalizeCommas.js";
import { isoToUnix } from "./ops/isoToUnix.js";
import { unixToIso } from "./ops/unixToIso.js";
import { fromFloat } from "./ops/fromFloat.js";
import { toFloat } from "./ops/toFloat.js";
import { jsonMinify } from "./ops/jsonMinify.js";
import { jsonBeautify } from "./ops/jsonBeautify.js";
import { extractStrings } from "./ops/extractStrings.js";
import { extractIPs } from "./ops/extractIPs.js";
import { extractUrls } from "./ops/extractUrls.js";
import { extractMacAddresses } from "./ops/extractMacAddresses.js";
import { defangUrls } from "./ops/defangUrls.js";
import { fangUrls } from "./ops/fangUrls.js";
import { changeIpFormat } from "./ops/changeIpFormat.js";
import { unixToWindowsFiletime } from "./ops/unixToWindowsFiletime.js";
import { windowsFiletimeToUnix } from "./ops/windowsFiletimeToUnix.js";
import { parseDateTimeOp } from "./ops/parseDateTime.js";
import { dateTimeDelta } from "./ops/dateTimeDelta.js";
import { translateDateTimeFormat } from "./ops/translateDateTimeFormat.js";
import { parseObjectIdTimestamp } from "./ops/parseObjectIdTimestamp.js";
import { parseUnixFilePermissions } from "./ops/parseUnixFilePermissions.js";
import { extractEmails } from "./ops/extractEmails.js";
import { extractDomains } from "./ops/extractDomains.js";
import { parseUserAgent } from "./ops/parseUserAgent.js";
import { parseX509Certificate } from "./ops/parseX509Certificate.js";
import { parseX509Crl } from "./ops/parseX509Crl.js";
import { jsonSortKeys } from "./ops/jsonSortKeys.js";
import { jsonExtractKeys } from "./ops/jsonExtractKeys.js";
import { extractMd5 } from "./ops/extractMd5.js";
import { jsonArrayLength } from "./ops/jsonArrayLength.js";
import { jsonStringValues } from "./ops/jsonStringValues.js";
import { jsonNumberValues } from "./ops/jsonNumberValues.js";
import { csvToJson } from "./ops/csvToJson.js";
import { jsonToCsv } from "./ops/jsonToCsv.js";
import { yamlToJson } from "./ops/yamlToJson.js";
import { jsonToYaml } from "./ops/jsonToYaml.js";
import { cborEncode } from "./ops/cborEncode.js";
import { cborDecode } from "./ops/cborDecode.js";
import { bsonEncode } from "./ops/bsonEncode.js";
import { bsonDecode } from "./ops/bsonDecode.js";
import { avroEncode } from "./ops/avroEncode.js";
import { avroDecode } from "./ops/avroDecode.js";
import { amfEncode } from "./ops/amfEncode.js";
import { amfDecode } from "./ops/amfDecode.js";
import { avroToJson } from "./ops/avroToJson.js";
import { bsonSerialise } from "./ops/bsonSerialise.js";
import { toTable } from "./ops/toTable.js";
import { toHtmlEntity } from "./ops/toHtmlEntity.js";
import { fromHtmlEntity } from "./ops/fromHtmlEntity.js";
import { convertImageFormat } from "./ops/convertImageFormat.js";
import { coverImage } from "./ops/coverImage.js";
import { cropImage } from "./ops/cropImage.js";
import { ditherImage } from "./ops/ditherImage.js";
import { extractExif } from "./ops/extractExif.js";
import { flipImage } from "./ops/flipImage.js";
import { fromHexdump } from "./ops/fromHexdump.js";
import { fromMessagePack } from "./ops/fromMessagePack.js";
import { toMessagePack } from "./ops/toMessagePack.js";
import { fromQuotedPrintable } from "./ops/fromQuotedPrintable.js";
import { toQuotedPrintable } from "./ops/toQuotedPrintable.js";
import { generateImage } from "./ops/generateImage.js";
import { htmlToTextOp } from "./ops/htmlToText.js";
import { generateQrCode } from "./ops/generateQrCode.js";
import { imageBrightnessContrast } from "./ops/imageBrightnessContrast.js";
import { imageFilter } from "./ops/imageFilter.js";
import { imageHueSaturationLightness } from "./ops/imageHueSaturationLightness.js";
import { imageOpacity } from "./ops/imageOpacity.js";
import { invertImage } from "./ops/invertImage.js";
import { jsonataQuery } from "./ops/jsonataQuery.js";
import { normaliseImage } from "./ops/normaliseImage.js";
import { xmlBeautify } from "./ops/xmlBeautify.js";
import { xmlMinify } from "./ops/xmlMinify.js";
import { protobufEncode } from "./ops/protobufEncode.js";
import { protobufDecode } from "./ops/protobufDecode.js";
import { stripHtmlTags } from "./ops/stripHtmlTags.js";
import { removeExif } from "./ops/removeExif.js";
import { resizeImage } from "./ops/resizeImage.js";
import { rotateImage } from "./ops/rotateImage.js";
import { sharpenImage } from "./ops/sharpenImage.js";
import { toHexdump } from "./ops/toHexdump.js";
import { renderImage } from "./ops/renderImage.js";
import { extractSha256 } from "./ops/extractSha256.js";
import { extractSha1 } from "./ops/extractSha1.js";
import { extractSha512 } from "./ops/extractSha512.js";
import { extractJwt } from "./ops/extractJwt.js";
import { extractCves } from "./ops/extractCves.js";
import { extractRegistryKeys } from "./ops/extractRegistryKeys.js";
import { analyseUuid } from "./ops/analyseUuid.js";
import { entropy } from "./ops/entropy.js";
import { ctph } from "./ops/ctph.js";
import { generateUuid } from "./ops/generateUuid.js";
import { fileTree } from "./ops/fileTree.js";
import { yaraRules } from "./ops/yaraRules.js";
import { chiSquareOp } from "./ops/chiSquare.js";
import { detectFileType } from "./ops/detectFileType.js";
import { elfInfo } from "./ops/elfInfo.js";
import { basicPreTriage } from "./ops/basicPreTriage.js";
import { basicTriage } from "./ops/basicTriage.js";
import { extractUnixTimestamps } from "./ops/extractUnixTimestamps.js";
import { extractIsoTimestamps } from "./ops/extractIsoTimestamps.js";
import { isoToDateOnly } from "./ops/isoToDateOnly.js";
import { isoWeekday } from "./ops/isoWeekday.js";
import { extractIPv6 } from "./ops/extractIPv6.js";
import { defangIPs } from "./ops/defangIPs.js";
import { fangIPs } from "./ops/fangIPs.js";
import { extractPorts } from "./ops/extractPorts.js";
import { dechunkHttpResponse } from "./ops/dechunkHttpResponse.js";
import { groupIPAddresses } from "./ops/groupIPAddresses.js";
import { dnsOverHttps } from "./ops/dnsOverHttps.js";
import { parseIPv6Address } from "./ops/parseIPv6Address.js";
import { ipv6TransitionAddresses } from "./ops/ipv6TransitionAddresses.js";
import { parseIPRange } from "./ops/parseIPRange.js";
import { stripHttpHeaders } from "./ops/stripHttpHeaders.js";
import { parseIPv4Header } from "./ops/parseIPv4Header.js";
import { parseTcpHeaderOp } from "./ops/parseTcpHeader.js";
import { parseTlsRecord } from "./ops/parseTlsRecord.js";
import { parseUdpHeaderOp } from "./ops/parseUdpHeader.js";
import { parseUri } from "./ops/parseUri.js";
import { stripIPv4Header } from "./ops/stripIPv4Header.js";
import { stripTcpHeader } from "./ops/stripTcpHeader.js";
import { stripUdpHeader } from "./ops/stripUdpHeader.js";
import { gzip } from "./ops/gzip.js";
import { gunzip } from "./ops/gunzip.js";
import { bzip2Compress } from "./ops/bzip2Compress.js";
import { bzip2Decompress } from "./ops/bzip2Decompress.js";
import { zip } from "./ops/zip.js";
import { unzip } from "./ops/unzip.js";
import { tar } from "./ops/tar.js";
import { untar } from "./ops/untar.js";
import { adler32Checksum } from "./ops/adler32.js";
import { crc32Checksum } from "./ops/crc32.js";
import { crc64Checksum } from "./ops/crc64.js";
import { fletcher8Checksum } from "./ops/fletcher8.js";
import { fletcher16Checksum } from "./ops/fletcher16.js";
import { fletcher32Checksum } from "./ops/fletcher32.js";
import { fletcher64Checksum } from "./ops/fletcher64.js";
import { analyseHash } from "./ops/analyseHash.js";
import { hashMd5 } from "./ops/hashMd5.js";
import { md4 } from "./ops/md4.js";
import { ripemd160 } from "./ops/ripemd160.js";
import { sha1 } from "./ops/sha1.js";
import { atbashCipher } from "./ops/atbashCipher.js";
import { affineCipherEncode } from "./ops/affineCipherEncode.js";
import { affineCipherDecode } from "./ops/affineCipherDecode.js";
import { a1z26CipherEncode } from "./ops/a1z26CipherEncode.js";
import { a1z26CipherDecode } from "./ops/a1z26CipherDecode.js";
import { baconCipherEncode } from "./ops/baconCipherEncode.js";
import { baconCipherDecode } from "./ops/baconCipherDecode.js";
import { bcryptParse } from "./ops/bcryptParse.js";
import { addTextToImage } from "./ops/addTextToImage.js";
import { blurImage } from "./ops/blurImage.js";
import { containImage } from "./ops/containImage.js";
import { imageMetadata } from "./ops/imageMetadata.js";
import { sha384 } from "./ops/sha384.js";
import { sha512 } from "./ops/sha512.js";
import { sha3_256 } from "./ops/sha3_256.js";
import { sha3_512 } from "./ops/sha3_512.js";
import { blake2b } from "./ops/blake2b.js";
import { blake2s } from "./ops/blake2s.js";
import { blake3 } from "./ops/blake3.js";
import { keccak } from "./ops/keccak.js";
import { sm3 } from "./ops/sm3.js";
import { whirlpool } from "./ops/whirlpool.js";
import { xxhash32 } from "./ops/xxhash32.js";
import { xxhash64 } from "./ops/xxhash64.js";
import { xxhash3 } from "./ops/xxhash3.js";
import { xxhash128 } from "./ops/xxhash128.js";
import { hmacSha1 } from "./ops/hmacSha1.js";
import { hmacSha256 } from "./ops/hmacSha256.js";
import { hmacSha384 } from "./ops/hmacSha384.js";
import { hmacSha512 } from "./ops/hmacSha512.js";
import { hkdf } from "./ops/hkdf.js";
import { pbkdf2 } from "./ops/pbkdf2.js";
import { scrypt } from "./ops/scrypt.js";
import { argon2d } from "./ops/argon2d.js";
import { argon2i } from "./ops/argon2i.js";
import { argon2id } from "./ops/argon2id.js";
import { argon2Verify } from "./ops/argon2Verify.js";
export const standardPlugin: Plugin = {
  pluginId: "plugins-standard",
  version: "0.1.0",
  register(registry: OperationRegistry): void {
    registry.register(toBase64);
    registry.register(fromBase64);
    registry.register(toBase32);
    registry.register(fromBase32);
    registry.register(toBase45);
    registry.register(fromBase45);
    registry.register(toBase62);
    registry.register(fromBase62);
    registry.register(toBase85);
    registry.register(fromBase85);
    registry.register(toBech32);
    registry.register(fromBech32);
    registry.register(toBase58);
    registry.register(fromBase58);
    registry.register(toBase92);
    registry.register(fromBase92);
    registry.register(toBraille);
    registry.register(fromBraille);
    registry.register(toPunycode);
    registry.register(fromPunycode);
    registry.register(toModhex);
    registry.register(fromModhex);
    registry.register(toMorseCode);
    registry.register(fromMorseCode);
    registry.register(toHex);
    registry.register(fromHex);
    registry.register(toBinary);
    registry.register(fromBinary);
    registry.register(toCharcode);
    registry.register(fromCharcode);
    registry.register(toDecimal);
    registry.register(fromDecimal);
    registry.register(toOctal);
    registry.register(fromOctal);
    registry.register(toHexContent);
    registry.register(fromHexContent);
    registry.register(dropBytes);
    registry.register(takeBytes);
    registry.register(dropNthBytes);
    registry.register(takeNthBytes);
    registry.register(removeNullBytes);
    registry.register(bitShiftLeft);
    registry.register(bitShiftRight);
    registry.register(urlEncode);
    registry.register(urlDecode);
    registry.register(reverse);
    registry.register(lowercase);
    registry.register(uppercase);
    registry.register(alternatingCaps);
    registry.register(expandAlphabetRange);
    registry.register(escapeString);
    registry.register(trim);
    registry.register(prepend);
    registry.register(append);
    registry.register(replace);
    registry.register(slice);
    registry.register(repeat);
    registry.register(padStart);
    registry.register(padEnd);
    registry.register(trimStart);
    registry.register(trimEnd);
    registry.register(length);
    registry.register(wordCount);
    registry.register(lineCount);
    registry.register(firstLine);
    registry.register(lastLine);
    registry.register(normalizeWhitespace);
    registry.register(removeBlankLines);
    registry.register(startsWith);
    registry.register(swapCase);
    registry.register(removeSpaces);
    registry.register(keepDigits);
    registry.register(removeDigits);
    registry.register(keepLetters);
    registry.register(removeLetters);
    registry.register(keepAlnum);
    registry.register(removeAlnum);
    registry.register(toTitleCase);
    registry.register(reverseLines);
    registry.register(sortLines);
    registry.register(uniqueLines);
    registry.register(trimLines);
    registry.register(toSnakeCase);
    registry.register(toKebabCase);
    registry.register(toCamelCase);
    registry.register(toPascalCase);
    registry.register(compactLines);
    registry.register(reverseWords);
    registry.register(sortWords);
    registry.register(uniqueWords);
    registry.register(removeVowels);
    registry.register(keepVowels);
    registry.register(normalizeNewlines);
    registry.register(endsWith);
    registry.register(includesText);
    registry.register(lowerFirst);
    registry.register(upperFirst);
    registry.register(removePunctuation);
    registry.register(keepPunctuation);
    registry.register(collapseDashes);
    registry.register(collapseUnderscores);
    registry.register(removeTabs);
    registry.register(tabsToSpaces);
    registry.register(spacesToTabs);
    registry.register(trimCommas);
    registry.register(trimQuotes);
    registry.register(surroundBrackets);
    registry.register(surroundQuotes);
    registry.register(rot13);
    registry.register(maskDigits);
    registry.register(removeNonAscii);
    registry.register(keepNonAscii);
    registry.register(reverseCharsInWords);
    registry.register(wordsToLines);
    registry.register(linesToWords);
    registry.register(linesToCsv);
    registry.register(csvToLines);
    registry.register(stripAccents);
    registry.register(removeDoubleQuotes);
    registry.register(removeSingleQuotes);
    registry.register(replaceNewlinesWithSpace);
    registry.register(replaceSpacesWithNewlines);
    registry.register(tabsToSingleSpace);
    registry.register(countUppercase);
    registry.register(countLowercase);
    registry.register(countAscii);
    registry.register(countNonAscii);
    registry.register(countNonEmptyLines);
    registry.register(firstWord);
    registry.register(lastWord);
    registry.register(removeCommas);
    registry.register(removeDots);
    registry.register(removeSemicolons);
    registry.register(keepHexChars);
    registry.register(removeHexChars);
    registry.register(onlyPrintableAscii);
    registry.register(removeControlChars);
    registry.register(collapseMultipleNewlines);
    registry.register(trimLeadingDots);
    registry.register(trimTrailingDots);
    registry.register(linesNumbered);
    registry.register(removeColons);
    registry.register(removeSlashes);
    registry.register(removePipes);
    registry.register(removeBackslashes);
    registry.register(removeAsterisks);
    registry.register(removeHashes);
    registry.register(removeAtSigns);
    registry.register(removeDollarSigns);
    registry.register(removePercents);
    registry.register(removeAmpersands);
    registry.register(removePluses);
    registry.register(removeEquals);
    registry.register(removeTildes);
    registry.register(removeCarets);
    registry.register(removeBackticks);
    registry.register(removeQuestionMarks);
    registry.register(removeExclamations);
    registry.register(removeParentheses);
    registry.register(removeBrackets);
    registry.register(removeBraces);
    registry.register(removeAngles);
    registry.register(removeDoubleSpaces);
    registry.register(linesTrimRight);
    registry.register(linesTrimLeft);
    registry.register(removeDigitsAndSpaces);
    registry.register(keepDigitsAndDots);
    registry.register(removeEmojis);
    registry.register(removeUnderscores);
    registry.register(removeHyphens);
    registry.register(removeSpacesAndTabs);
    registry.register(keepWhitespace);
    registry.register(countTabs);
    registry.register(countSpaces);
    registry.register(countCommas);
    registry.register(countDots);
    registry.register(countColons);
    registry.register(countSemicolons);
    registry.register(countSlashes);
    registry.register(countBackslashes);
    registry.register(countPluses);
    registry.register(countDashes);
    registry.register(countQuestionMarks);
    registry.register(countExclamations);
    registry.register(countBrackets);
    registry.register(countParentheses);
    registry.register(countQuotes);
    registry.register(countUnderscores);
    registry.register(onlyLettersAndSpaces);
    registry.register(onlyAlnumAndSpaces);
    registry.register(sum);
    registry.register(subtract);
    registry.register(multiply);
    registry.register(divide);
    registry.register(removeCurrencySymbols);
    registry.register(removeMathSymbols);
    registry.register(normalizeCommas);
    registry.register(isoToUnix);
    registry.register(unixToIso);
    registry.register(fromFloat);
    registry.register(toFloat);
    registry.register(unixToWindowsFiletime);
    registry.register(windowsFiletimeToUnix);
    registry.register(parseDateTimeOp);
    registry.register(dateTimeDelta);
    registry.register(translateDateTimeFormat);
    registry.register(parseObjectIdTimestamp);
    registry.register(parseUnixFilePermissions);
    registry.register(changeIpFormat);
    registry.register(extractUnixTimestamps);
    registry.register(extractIsoTimestamps);
    registry.register(isoToDateOnly);
    registry.register(isoWeekday);
    registry.register(extractEmails);
    registry.register(extractDomains);
    registry.register(parseUserAgent);
    registry.register(parseX509Certificate);
    registry.register(parseX509Crl);
    registry.register(extractMd5);
    registry.register(extractSha1);
    registry.register(extractSha256);
    registry.register(extractSha512);
    registry.register(extractJwt);
    registry.register(extractCves);
    registry.register(extractRegistryKeys);
    registry.register(analyseUuid);
    registry.register(entropy);
    registry.register(ctph);
    registry.register(generateUuid);
    registry.register(fileTree);
    registry.register(yaraRules);
    registry.register(chiSquareOp);
    registry.register(detectFileType);
    registry.register(elfInfo);
    registry.register(basicPreTriage);
    registry.register(basicTriage);
    registry.register(jsonMinify);
    registry.register(jsonBeautify);
    registry.register(jsonSortKeys);
    registry.register(jsonExtractKeys);
    registry.register(jsonArrayLength);
    registry.register(jsonStringValues);
    registry.register(jsonNumberValues);
    registry.register(amfEncode);
    registry.register(amfDecode);
    registry.register(avroToJson);
    registry.register(bsonSerialise);
    registry.register(toTable);
    registry.register(toHtmlEntity);
    registry.register(fromHtmlEntity);
    registry.register(toMessagePack);
    registry.register(fromMessagePack);
    registry.register(toQuotedPrintable);
    registry.register(fromQuotedPrintable);
    registry.register(xmlBeautify);
    registry.register(xmlMinify);
    registry.register(stripHtmlTags);
    registry.register(jsonataQuery);
    registry.register(csvToJson);
    registry.register(jsonToCsv);
    registry.register(yamlToJson);
    registry.register(jsonToYaml);
    registry.register(cborEncode);
    registry.register(cborDecode);
    registry.register(bsonEncode);
    registry.register(bsonDecode);
    registry.register(avroEncode);
    registry.register(avroDecode);
    registry.register(protobufEncode);
    registry.register(protobufDecode);
    registry.register(toHexdump);
    registry.register(fromHexdump);
    registry.register(htmlToTextOp);
    registry.register(extractStrings);
    registry.register(extractIPs);
    registry.register(extractIPv6);
    registry.register(extractMacAddresses);
    registry.register(defangIPs);
    registry.register(fangIPs);
    registry.register(extractPorts);
    registry.register(dechunkHttpResponse);
    registry.register(groupIPAddresses);
    registry.register(dnsOverHttps);
    registry.register(parseIPv6Address);
    registry.register(ipv6TransitionAddresses);
    registry.register(parseIPRange);
    registry.register(stripHttpHeaders);
    registry.register(parseIPv4Header);
    registry.register(parseTcpHeaderOp);
    registry.register(parseTlsRecord);
    registry.register(parseUdpHeaderOp);
    registry.register(parseUri);
    registry.register(stripIPv4Header);
    registry.register(stripTcpHeader);
    registry.register(stripUdpHeader);
    registry.register(gzip);
    registry.register(gunzip);
    registry.register(bzip2Compress);
    registry.register(bzip2Decompress);
    registry.register(zip);
    registry.register(unzip);
    registry.register(tar);
    registry.register(untar);
    registry.register(addTextToImage);
    registry.register(blurImage);
    registry.register(containImage);
    registry.register(convertImageFormat);
    registry.register(coverImage);
    registry.register(cropImage);
    registry.register(ditherImage);
    registry.register(extractExif);
    registry.register(flipImage);
    registry.register(generateImage);
    registry.register(generateQrCode);
    registry.register(imageBrightnessContrast);
    registry.register(imageFilter);
    registry.register(imageHueSaturationLightness);
    registry.register(imageOpacity);
    registry.register(imageMetadata);
    registry.register(invertImage);
    registry.register(normaliseImage);
    registry.register(removeExif);
    registry.register(renderImage);
    registry.register(resizeImage);
    registry.register(rotateImage);
    registry.register(sharpenImage);
    registry.register(extractUrls);
    registry.register(defangUrls);
    registry.register(fangUrls);
    registry.register(adler32Checksum);
    registry.register(crc32Checksum);
    registry.register(crc64Checksum);
    registry.register(fletcher8Checksum);
    registry.register(fletcher16Checksum);
    registry.register(fletcher32Checksum);
    registry.register(fletcher64Checksum);
    registry.register(analyseHash);
    registry.register(hashMd5);
    registry.register(md4);
    registry.register(ripemd160);
    registry.register(sha1);
    registry.register(atbashCipher);
    registry.register(affineCipherEncode);
    registry.register(affineCipherDecode);
    registry.register(a1z26CipherEncode);
    registry.register(a1z26CipherDecode);
    registry.register(baconCipherEncode);
    registry.register(baconCipherDecode);
    registry.register(bcryptParse);
    registry.register(sha384);
    registry.register(sha512);
    registry.register(sha3_256);
    registry.register(sha3_512);
    registry.register(blake2b);
    registry.register(blake2s);
    registry.register(blake3);
    registry.register(keccak);
    registry.register(sm3);
    registry.register(whirlpool);
    registry.register(xxhash32);
    registry.register(xxhash64);
    registry.register(xxhash3);
    registry.register(xxhash128);
    registry.register(hmacSha1);
    registry.register(hmacSha256);
    registry.register(hmacSha384);
    registry.register(hmacSha512);
    registry.register(hkdf);
    registry.register(pbkdf2);
    registry.register(scrypt);
    registry.register(argon2d);
    registry.register(argon2i);
    registry.register(argon2id);
    registry.register(argon2Verify);
    registry.register(sha224);
    registry.register(sha256);
  }
};
